services:
  backend:
    build: backend/
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: False
      DJANGO_SECRET_KEY: 'django-insecure-f)=bss298b3pym1leu#vm@5+ca3i=d_420w_578%5x!10aXnis'
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost:8080,http://0.0.0.0:8080,http://127.0.0.1:8080"
  frontend:
    build: frontend/
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
