export const characters = {
    "steve": "Steve",
    "sonic": "Sonic",
    "mr_game_and_watch": "Mr. Game & Watch",
    "snake": "Snake",
    "pyra_mythra": "Pyra & Mythra",
    "r_o_b": "R.O.B.",
    "peach_daisy": "Peach/Daisy",
    "fox": "Fox",
    "diddy_kong": "Diddy Kong",
    "joker": "Joker",
    "kazuya": "Kazuya",
    "min_min": "Min Min",
    "cloud": "Cloud",
    "yoshi": "Yoshi",
    "samus_dark_samus": "Samus/Dark Samus",
    "palutena": "Palutena",
    "pikachu": "Pikachu",
    "sora": "Sora",
    "roy": "Roy",
    "wario": "Wario",
    "wolf": "Wolf",
    "mario": "Mario",
    "pac_man": "Pac Man",
    "pokemon_trainer": "Pokémon Trainer",
    "shulk": "Shulk",
    "bayonetta": "Bayonetta",
    "corrin": "Corrin",
    "lucina": "Lucina",
    "terry": "Terry",
    "zero_suit_samus": "Zero Suit Samus",
    "sheik": "Sheik",
    "ryu": "Ryu",
    "olimar": "Olimar",
    "greninja": "Greninja",
    "falco": "Falco",
    "mii_brawler": "Mii Brawler",
    "sephiroth": "Sephiroth",
    "young_link": "Young Link",
    "luigi": "Luigi",
    "captain_falcon": "Captain Falcon",
    "pit": "Pit",
    "dark_pit": "Dark Pit",
    "byleth": "Byleth",
    "rosalina_and_luma": "Rosalina & Luma",
    "hero": "Hero",
    "ken": "Ken",
    "toon_link": "Toon Link",
    "ness": "Ness",
    "mega_man": "Mega Man",
    "inkling": "Inkling",
    "meta_knight": "Meta Knight",
    "ice_climbers": "Ice Climbers",
    "incinerator": "Incinerator",
    "pichu": "Pichu",
    "chrom": "Chrom",
    "marth": "Marth",
    "link": "Link",
    "lucario": "Lucario",
    "mii_gunner": "Mii Gunner",
    "bowser": "Bowser",
    "jigglypuff": "Jigglypuff",
    "lucas": "Lucas",
    "banjo_and_kazooie": "Banjo and Kazooie",
    "wii_fit_trainer": "Wii Fit Trainer",
    "ridley": "Ridley",
    "duck_hunt": "Duck Hunt",
    "mewtwo": "Mewtwo",
    "robin": "Robin",
    "donkey_kong": "Donkey Kong",
    "isabelle": "Isabelle",
    "bowser_jr": "Bowser Jr.",
    "ike": "Ike",
    "villager": "Villager",
    "zelda": "Zelda",
    "simon_richter": "Simon/Richter",
    "kirby": "Kirby",
    "mii_swordfighter": "Mii Swordfighter",
    "piranha_plant": "Piranha Plant",
    "dr_mario": "Dr. Mario",
    "king_dedede": "King Dedede",
    "king_k_rool": "King K. Rool",
    "little_mac": "Little Mac",
    "ganondorf": "Ganondorf",
};

export function getNameFromApi(name: string): string {
    return characters[name];
}
