name: Deploy to ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

permissions: 
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::214277676991:role/github-ecs-oidc-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build. tag, and push backend image
        id: backend-image
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_BACKEND }}
        run: |
          docker build -t $ECR_REPOSITORY:latest ./backend
          docker tag $ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Build, tag, and push frontend image
        id: frontend-image
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_FRONTEND }}
        run: |
          docker build -t $ECR_REPOSITORY:latest ./frontend
          docker tag $ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --task-definition ${{ secrets.ECS_TASK_DEFINITION }} \
            --force-new-deployment
